name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */24 * * *" # Runs once a day
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          username: its-gizmo47
          count_private: true
          include_all_commits: true

      - name: Commit and Push README update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update GitHub Stats"
          git push
